---
- name: "AIX CHECK HARDENING" 
  hosts: all
  gather_facts: no
  collections:
  - ibm.power_aix

  tasks:
  - name: "Collect OS version for host {{ inventory_hostname }}"
    command: "oslevel -s"
    register: oslevel_info
    #when:
     #- ansible_system == "AIX"
        
  - name: "Show oslevel output"
    debug:
      var: oslevel_info
      
  - name: "Set os_level fact from registered output"
    set_fact:
      os_level: "{{ oslevel_info.stdout }}"
    #when:
     #- ansible_system == "AIX"
        
  - name: Check Trusted Execution Services
    command: trustchk -p
    register: stderr_lines

  - name: "Show Truted Execution Results"
    debug:
      var: stderr_lines

  - name: "Show TE Results"
    set_fact:
      result:  "{{ stderr_lines }}"
  
  - name: Check current security rules applied
    command: aixpert -t 
    register: stderr

  - name: "Show AIXPERT Results"
    debug:
      var: stderr

  - name: "Set AIXPERT Results"
    set_fact: 
      result:  "{{stderr}}"

tasks:
  - name: Install aixpert.py onto target
    copy:
     src: aixpert.py
     dest: /usr/sbin/vioshc.py
     mode: '0755'
