---
- name: "AIX HARDENING DEFAULT" 
  hosts: all
  gather_facts: no
  collections:
  - ibm.power_aix

  tasks:
  - name: "Run AIXPERT DEFAULT SECURITY RULES for host {{ inventory_hostname }}"
    command: "aixpert -l default"
    register: stderr

  - name: "Show AIXPERT DEFAULT Results"
    debug:
      var: stderr

  - name: "Set AIXPERT DEFAULT Results"
    set_fact: 
      result:  "{{stderr}}"
