---
- name: "Run AIXPERT script"
  hosts: all
  tasks: 
  import_module:
     name: aixpert.py
  # ansible.builtin.script:
  #executable: python3
  #cmd: aixpert.py
  
     collections:
      - ibm.power_aix
