---
- name: "AIX CHECK HARDENING" 
  hosts: all
  gather_facts: no
  collections:
  - ibm.power_aix

  tasks:
  - name: "Collect OS version for host {{ inventory_hostname }}"
    command: "oslevel -s"
    register: oslevel_info
    #when:
     #- ansible_system == "AIX"
        
  - name: "Show oslevel output"
    debug:
      var: oslevel_info
      
  - name: "Set os_level fact from registered output"
    set_fact:
      os_level: "{{ oslevel_info.stdout }}"
    #when:
     #- ansible_system == "AIX"
        
  - name: Check Trusted Execution Services
    command: trustchk -p
    register: stderr_lines

  - name: "Show Truted Execution Results"
    debug:
      var: stderr_lines

  - name: "Set TE Results"
    set_fact:
      result:  "{{ stderr_lines }}"
  
  - name: Check current security rules applied
    command: aixpert -t 
    register: stderr

  - name: "Show AIXPERT Results"
    debug:
      var: stderr

  - name: "Set AIXPERT Results"
    set_fact: 
      result:  "{{stderr}}"

  #- name: "Check FLRTVC"
   # ibm.power_aix.flrtvc:

  - name: 'FLRTVC on AIX playbook'
  hosts: all
  gather_facts: no
  vars:
    apar: sec
    path: /usr/sys/inst.images
    check: no
    download_only: yes
    extend: yes

  collections:
  - ibm.power_aix

  tasks:
  - name: Check for wget command
   yum:
    name: "wget"
     state: latest
   - name: 'FLRTVC' 
    flrtvc:
      path: "{{ path }}"
      verbose: yes
       apar: "{{ apar }}"
       force: no
       clean: False
       check_only: "{{ check }}"
       download_only: "{{ download_only }}"
       extend_fs: "{{ extend }}"
     register: result
   - debug: var=result
