---
- name: "FLRTVC on AIX playbook"
  hosts: all
  gather_facts: no
  collections:
  - ibm.power_aix
  
  tasks:
  - name: "FLRTVC"
      ibm.power_aix.aix_flrtvc:
      targets: 'ansible-4-ansible-tower'
      path: /usr/sys/inst.images
      verbose: yes
      apar: all
      force: no
      clean: False
      check_only: yes
        #download_only: no
      register: result
      debug: 
        var=result
