---
- name: "Run AIXPERT script"
  hosts: all
  collections:
  - ibm.power_aix
  tasks:

# CHECK VULNERABILITIES
  - import_plugins:
     name: aixpert.py
     ansible.builtin.import_playbook module

