---
- name: "Run AIXPERT script"
  hosts: all
  gather_facts: no
  collections:
  - ibm.power_aix

  tasks:

  - name: "Check oslevel of AIX system"
    shell: "oslevel -s"

  - name: "Check Trusted Execution Services"
    command: trustchk -p
  
  - name: "Check current security rules applied"
    command: aixpert -t 

  - name: "Check FLRTVC"
    ibm.power_aix.flrtvc:





