---
- name: "AIX-CIS-BENCHMARK USING AIXPERT MODULE" 
  hosts: all
  gather_facts: no
  collections:
  - ibm.power_aix

  tasks:
  - name: "Save default level rules in normal format"
    aixpert:
     mode: save
     level: default
     norm_fmt_file: /home/mtesta/norm.xml

  - name: "Save high level rules in normal format"
    aixpert:
     mode: save
     level: high
     norm_fmt_file: /home/mtesta/high.xml

  - name: "Check and log security settings for host {{ inventory_hostname }}"
    command: "tail -50 /etc/security/aixpert/check_report.txt"
    register: "stdout_lines"

  #- name: "Apply using saved profile"
   # aixpert:
    # mode: apply
     #profile: /home/mtesta/norm.xml

  #- name: "Undo the settings"
   # aixpert:
    # mode: undo

  #- name: "Check the settings match the provided profile"
   # aixpert:
    # mode: check
     #profile: /home/mtesta/high.xml

  #- name: "Query the settings"
   # aixpert:
    # mode: query
