---
- name: "AIX-CIS-BENCHMARK" 
  hosts: all
  gather_facts: no
  #vars:
    #cmd: '/usr/sbin/rmitab'
    #inittab_v: 
    #- "wrtitesrv"
    #- "i4ls"
    #- "pmd"
    #- "httpdlite"
    #- "rcnfs"
    #- "rcncs"
    #- "qdaemon"
    #- "lpd"
    #- "piobe"
    #- "dt" 
  collections:
  - ibm.power_aix

  tasks:
  - name: "Check daemons enabled on innitab"
    command: lsitab {{ item }}
    loop:
    - writesrv
    - i4ls
    - pmd
    - httpdlite
    - rcnfs
    - rcncs
    - qdaemon
    - lpd
    - piobe
    - dt
    register: lsitab
    ignore_errors: yes
    changed_when: false
      
  #- name: "Remove entry for inittab daemons" 
   #   inittab:
    #    state: absent
     #   name: "{{inittab_v}}"
        #command: {{cmd}}
        
  - name: "Remove daemons from inittab"
    command: rmitab {{ item.item }}
    loop: "{{ lsitab.results }}"
    when: item.rc == 0
    loop_control:
      label: "{{ item.item }}"
